FROM php:8.4-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
        # dependencies (runtime required)
        wget \
        zip \
        unzip \
	    git \
        libxext6 \
        fontconfig \
        xfonts-base \
        xfonts-75dpi \
        libxrender1 \
        libaio1t64 \
        libjpeg62-turbo \
        libpq5 \
        libzip5\
        libmcrypt4 \
        librdkafka1 \
        # dependencies (build required, will be purge after build)
        libjpeg62-turbo-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        libmcrypt-dev \
        libxml2-dev \
        zlib1g-dev \
        libpng-dev \
        libpq-dev \
        libzip-dev \
        librdkafka-dev \
    # Install Node.js LTS
    && curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    # kafka
    && pecl install redis rdkafka \
    && docker-php-ext-enable redis rdkafka \
    # build php extension
    && docker-php-ext-install \
        pdo pdo_pgsql mysqli pdo_mysql \
        bcmath soap sockets sysvmsg sysvsem sysvshm zip gd \
    # remove *-dev packages
    && apt-get purge -y --auto-remove \
        libjpeg62-turbo-dev libssl-dev libcurl4-openssl-dev \
        libmcrypt-dev libxml2-dev zlib1g-dev libpng-dev libpq-dev libzip-dev librdkafka-dev \
    # clean up
    && docker-php-source delete \
    && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /tmp/pear

##
# Oracle Installation
###
ENV LD_LIBRARY_PATH="/opt/oracle/instantclient_19_19" \
    ORACLE_HOME="/opt/oracle/instantclient_19_19" \
    OCI_HOME="/opt/oracle/instantclient_19_19" \
    OCI_LIB_DIR="/opt/oracle/instantclient_19_19" \
    OCI_INCLUDE_DIR="/opt/oracle/instantclient_19_19/sdk/include" \
    OCI_VERSION=19

RUN --mount=type=bind,source=packages/oracle,target=/tmp/oracle \
    mkdir -p /opt/oracle \
    && unzip /tmp/oracle/instantclient-basic-linux-arm64.zip -d /opt/oracle \
    && unzip /tmp/oracle/instantclient-sdk-linux-arm64.zip -d /opt/oracle \
    && echo /opt/oracle/instantclient_19_19 > /etc/ld.so.conf.d/oracle-instantclient.conf \
    && ldconfig \
    && ln -s /usr/lib/aarch64-linux-gnu/libaio.so.1t64 /usr/lib/aarch64-linux-gnu/libaio.so.1 \
    && echo 'instantclient,/opt/oracle/instantclient_19_19' | pecl install oci8 \
    && echo "extension=oci8.so" >> /usr/local/etc/php/conf.d/oci8.ini \
    && echo 'instantclient,/opt/oracle/instantclient_19_19' | pecl install pdo_oci \
    && echo "extension=pdo_oci.so" > /usr/local/etc/php/conf.d/pdo_oci.ini \
    && docker-php-ext-enable pdo_pgsql pdo_mysql \
    && rm -rf /opt/oracle/instantclient_19_19/sdk \
    && rm -rf /tmp/pear \
    && ldconfig

# install wkhtmltopdf ARM64 base
RUN curl -fsSL https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_arm64.deb -o /tmp/wkhtmltox.deb \
    && dpkg -i /tmp/wkhtmltox.deb \
    && rm /tmp/wkhtmltox.deb

# copy composer runtime build into this image
COPY --from=composer:2.8.8 /usr/bin/composer /usr/bin/composer
