FROM php:8.3.20-fpm

RUN apt-get update && \
    apt-get install -y \
        # php dependencies
        libssl-dev \
        libcurl4-openssl-dev \
        # postgresql dependencies
        libpq-dev

RUN docker-php-ext-install \
    pdo_pgsql \
    pdo_mysql \
    bcmath

RUN docker-php-ext-enable pdo_pgsql pdo_mysql

# Clean up
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*