FROM nginx:latest

RUN apt-get update && \
    apt-get install -y \
        net-tools \
        iputils-ping \
        telnet

# Clean up
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*